spring.application.name=spring-ai
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o


# actuator metrics

# To expose only the metrics endpoint along with health
#management.endpoints.web.exposure.include=health,metrics

# OR to expose all available actuator endpoints (useful for development) - > Below is enabled
management.endpoints.web.exposure.include=*
